### ISSUE TITLE
Dynamically changing appid / secret 

### ISSUE THREAD

**Issue by jakubvojacek** [contributte/facebook#1]
Hello,

I would like to be loading appId & secret from 3rd party API instead of neon. That is currently not possible since `Facebook` instance is created directly in Nette configurator.

 Would you be opened to adding `setFacebook()` method to `FacebookLogin`? Or maybe even creating `Facebook` lazily, only when really needed. And then apart from neon it would be possible to use `FacebookLogin->setAppId()`, `FacebookLogin->setSecret();`

I could try to make a pull request I guess.

**Comment by f3l1x** [comment]
Hi, thanks for the issues, sorry I'm late. Well, I like your proposal, but I don't want to implement `setFacebook` to keep encapsulation.

Do you have any other idea?

**Comment by f3l1x** [comment]
ping @jakubvojacek

**Comment by vody105** [comment]
Nyní je FB a FBFactory jako služba, takže bys měl být schopen ji rozšířit
