### ISSUE TITLE
Inconsistent example

### ISSUE THREAD

**Issue by adaamz** [contributte/facebook#7]
Hi,
in docs is this example
```php
$token = $this->facebookLogin->getAccessToken(); // returns AccessToken
$this->user->login('facebook', $this->facebookLogin->getMe($token, ['first_name', 'last_name', 'email', 'gender']));
```
but FacebookLogin::getMe strictly accepts only `string $accessToken`.
It should be changed in docs or method getMe should accept both string|AccessToken.

**Comment by f3l1x** [comment]
Hi. Thank you. We will fix it.

**Comment by f3l1x** [comment]
Could you please take a look? @vody105
